### ISSUE TITLE
Pipeline function 'googleStorageUpload' not working in post block

### ISSUE THREAD

**Issue by videnovnebojsa** [jenkinsci/google-storage-plugin#42]
If we use declarative Jenkins pipeline and move `googleStorageUpload` to `post` block, function never gets executed if the preceding stage uses one of these 
```
sh 'exit ' # or
currentBuild.result = 'FAILURE' # or
error 'Fail build message'
```
There is no even output like it gets swallowed. 

Example of the job:
```
pipeline {
  agent { label 'agent_label' }

  stages {
    stage('Uploading') {
      steps {
        sh 'touch test.json'
        sh 'exit 1'
      }
    }
  }

  post {
    always {
      script {
        googleStorageUpload bucket: 'gs://bucket-name', credentialsId: 'credentialsId', pattern: 'test.json'
      }
    }
  }
}
```
If you comment out `sh 'exit 1'`,  provided file gets uploaded to Google Storage.

Tested on: 
* Jenkins ver. 2.89.3.
* Google Cloud Storage plugin version 1.0

**Comment by agoulti** [comment]
This is done and a new release 1.1 is rolling out.
Thanks for reporting this!

**Comment by tshasc** [comment]
Sorry for disturb, seems from UI, there is a check called "For failed jobs", what is the parameter name if  I want to set it when trigger  googleStorageUpload from pipeline script?

**Comment by agoulti** [comment]
That option is only accessible for the Freestyle Post- step, not the pipeline version.
As of Version 1.1 it should default to true, meaning that whenever this step is reached, it should perform the upload regardless of the state of the build.

In order to ensure that this step is reached, you can use pipeline constructs: see for example Nebojsa's example above using the "always" clause. It should be working as of version 1.1 to always upload the files, even on a failed build.

Does that answer your question?

**Comment by tshasc** [comment]
Thanks for your reply.
I have another question maybe unrelated to this.
What is the default search path for googleStorageUpload?
I found the log for job and pipeline are different as below, 
/var/lib/jenkins/jobs/android-build/builds/701/build-log.txt
/var/lib/jenkins/jobs/android-build-pipeline/builds/701/log

i used below
script {
                googleStorageUpload bucket: 'gs://****/${JOB_NAME}/${BUILD_ID}', credentialsId: '****', pattern: 'log'
            }
 but it gave me 
ERROR: [Google Cloud Storage Plugin] No artifacts found matching pattern: log

any ideas?

**Comment by agoulti** [comment]
From what I remember, it would be the current directory of wherever Jenkins ends up executing the command.

What do you get if you do "sh 'ls'" just before the attempted upload?

**Comment by tshasc** [comment]
I tried that, obviously its current directory is on slave node instead of the master.
is this a known issue or I can set the path to master?
seems I did nothing when using this from UI for normal jenkins Jobs

**Comment by tshasc** [comment]
I got some progress and be able to run this on master under current job folder, but still can't find the right pattern to upload, any ideas?

https://github.com/jenkinsci/google-storage-plugin/issues/44

**Comment by mselvam-clgx** [comment]
Hi ,
 I'm working on a scripted pipeline and need to upload a folder after building from jenkins into gcp bucket. I'm new to this can someone help me on how to do this.
need to add this as a stage and ii have enabled the cloudstorageplugin for google in jenkins

**Comment by Moni3099** [comment]
Hi ,
 I'm working on a scripted pipeline and need to upload a folder after building from jenkins into gcp bucket. I'm new to this can someone help me on how to do this.
need to add this as a stage and ii have enabled the cloudstorageplugin for google in jenkins

**Comment by asuri3** [comment]
> Hi ,
> I'm working on a scripted pipeline and need to upload a folder after building from jenkins into gcp bucket. I'm new to this can someone help me on how to do this.
> need to add this as a stage and ii have enabled the cloudstorageplugin for google in jenkins

+1
